/* generated by PANINI → C */
#include <stdio.h>
int factorial(int n) {
  if ((n <= 1)) {
    return 1;
  } else {
    return (n * factorial((n - 1)));
  }
}
int main() {
  int result = 0;
  result = factorial(6);
  printf("%d\n", result);
  return result;
}
