/* tree-rev: 2026.08.28 */
/* Copyright (C) 1993-2026 Abhishek Choudhary
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
/** Emit PANINI IR as Python / C / Fortran / WGSL-shaped text. Subset, not full ABI. */

function ident(name) {
  return String(name || "anon").replace(/[^A-Za-z0-9_]/g, "_");
}

function emitExprPy(e) {
  if (!e) return "None";
  if (e.op === "const") return JSON.stringify(e.value);
  if (e.op === "load") return ident(e.name);
  if (e.op === "bin") return `(${emitExprPy(e.left)} ${e.operator === "AND" ? "and" : e.operator === "OR" ? "or" : e.operator} ${emitExprPy(e.right)})`;
  if (e.op === "call") {
    const n = e.callee?.name === "PRINT" || e.callee?.op === "load" && e.callee.name === "PRINT" ? "print" : emitExprPy(e.callee);
    return `${n}(${(e.args || []).map(emitExprPy).join(", ")})`;
  }
  if (e.op === "list") return "[" + (e.elements || []).map(emitExprPy).join(", ") + "]";
  return "None";
}

function emitStmtPy(s, pad) {
  if (!s) return pad + "pass";
  if (s.op === "return") return pad + "return " + emitExprPy(s.arg);
  if (s.op === "expr") return pad + emitExprPy(s.value);
  if (s.op === "assign") return pad + emitExprPy(s.target) + " = " + emitExprPy(s.value);
  if (s.op === "if") return pad + "if " + emitExprPy(s.test) + ":\n" + emitBlockPy(s.then, pad + "    ") + (s.else?.length ? "\n" + pad + "else:\n" + emitBlockPy(s.else, pad + "    ") : "");
  if (s.op === "while") return pad + "while " + emitExprPy(s.test) + ":\n" + emitBlockPy(s.body, pad + "    ");
  return pad + "pass";
}

function emitBlockPy(stmts, pad) {
  const xs = (stmts || []).map((s) => emitStmtPy(s, pad));
  return xs.length ? xs.join("\n") : pad + "pass";
}

export function emitPython(ir, { torch = false } = {}) {
  const lines = ["# generated by PANINI → Python"];
  if (torch) lines.push("import torch");
  for (const fn of ir.functions || []) {
    lines.push(`def ${ident(fn.name)}(${(fn.params || []).map(ident).join(", ")}):`);
    lines.push(emitBlockPy(fn.body, "    "));
    lines.push("");
  }
  if ((ir.functions || []).some((f) => f.name === "main")) lines.push("if __name__ == '__main__':\n    main()");
  return lines.join("\n") + "\n";
}

function emitExprC(e) {
  if (!e) return "0";
  if (e.op === "const") return typeof e.value === "string" ? JSON.stringify(e.value) : String(e.value);
  if (e.op === "load") return ident(e.name);
  if (e.op === "bin") return `(${emitExprC(e.left)} ${e.operator} ${emitExprC(e.right)})`;
  if (e.op === "call") {
    const isPrint = e.callee?.name === "PRINT" || (e.callee?.op === "load" && e.callee.name === "PRINT");
    if (isPrint) {
      const args = e.args || [];
      if (args.length === 1 && args[0].op === "const" && typeof args[0].value === "string")
        return `printf("%s\\n", ${JSON.stringify(args[0].value)})`;
      return `printf("%d\\n", ${(args).map(emitExprC).join(", ") || "0"})`;
    }
    return `${emitExprC(e.callee)}(${(e.args || []).map(emitExprC).join(", ")})`;
  }
  return "0";
}

function emitStmtC(s, pad) {
  if (!s) return pad + ";";
  if (s.op === "return") return pad + "return " + emitExprC(s.arg) + ";";
  if (s.op === "expr") return pad + emitExprC(s.value) + ";";
  if (s.op === "assign") return pad + emitExprC(s.target) + " = " + emitExprC(s.value) + ";";
  if (s.op === "if") {
    let out = pad + "if (" + emitExprC(s.test) + ") {\n" + emitBlockC(s.then, pad + "  ") + "\n" + pad + "}";
    if (s.else && s.else.length) out += " else {\n" + emitBlockC(s.else, pad + "  ") + "\n" + pad + "}";
    return out;
  }
  if (s.op === "while") return pad + "while (" + emitExprC(s.test) + ") {\n" + emitBlockC(s.body, pad + "  ") + "\n" + pad + "}";
  return pad + ";";
}

function emitBlockC(stmts, pad) {
  return (stmts || []).map((s) => emitStmtC(s, pad)).join("\n");
}

function collectAssigns(stmts, set) {
  for (const s of stmts || []) {
    if (s && s.op === "assign" && s.target && s.target.name) set.add(s.target.name);
    if (s && s.then) collectAssigns(s.then, set);
    if (s && s.else) collectAssigns(s.else, set);
    if (s && s.body) collectAssigns(s.body, set);
  }
}

export function emitC(ir) {
  const lines = ["/* generated by PANINI → C */", "#include <stdio.h>"];
  for (const fn of ir.functions || []) {
    const params = (fn.params || []).map(ident);
    lines.push(`int ${ident(fn.name)}(${params.map((p) => "int " + p).join(", ")}) {`);
    const locals = new Set();
    collectAssigns(fn.body, locals);
    for (const p of params) locals.delete(p);
    for (const n of locals) lines.push(`  int ${n} = 0;`);
    lines.push(emitBlockC(fn.body, "  "));
    lines.push("}");
  }
  return lines.join("\n") + "\n";
}

export function emitFortran(ir) {
  const lines = ["! generated by PANINI → Fortran"];
  for (const fn of ir.functions || []) {
    const name = ident(fn.name);
    if (name === "main") {
      lines.push("PROGRAM PANINI_MAIN");
      lines.push("  INTEGER :: R");
      lines.push("  R = 0");
      for (const s of fn.body || []) {
        if (s.op === "return") lines.push("  R = " + emitExprC(s.arg));
        if (s.op === "expr" && s.value?.op === "call") lines.push("  PRINT *, " + emitExprC(s.value.args?.[0] || s.value));
      }
      lines.push("END PROGRAM PANINI_MAIN");
    } else {
      lines.push(`INTEGER FUNCTION ${name}(${(fn.params || []).map(ident).join(", ")})`);
      lines.push(emitBlockC(fn.body, "  ").replace(/return /g, name + " = ").replace(/;/g, ""));
      lines.push(`END FUNCTION ${name}`);
    }
  }
  return lines.join("\n") + "\n";
}

export function emitWgslCompute() {
  return `@compute @workgroup_size(8, 8)
fn gemm(@builtin(global_invocation_id) gid: vec3<u32>) {
  // placeholder tiled GEMM workgroup — bind groups filled by runtime/webgpu.js
}
`;
}
