(module
  (memory (export "memory") 2)
  (global $heap (mut i32) (i32.const 4096))
  (global $sp (mut i32) (i32.const 131072))
  (func $calloc (export "calloc") (param $n i32) (param $sz i32) (result i32)
    (local $p i32)
    (global.get $heap)
    (local.set $p)
    (global.get $heap)
    (local.get $n)
    (local.get $sz)
    (i32.mul)
    (i32.add)
    (global.set $heap)
    (local.get $p)
    (return)
  )
  (func $compute (export "compute") (param $x i32) (result i32)
    (local $t0 i32)
    (local $ret i32)
    (global.get $sp)
    (i32.const 8)
    (i32.sub)
    (global.set $sp)
    (global.get $sp)
    (i32.const 0)
    (i32.add)
    (local.get $x)
    (i32.store)
    (global.get $sp)
    (i32.const 4)
    (i32.add)
    (global.get $sp)
    (i32.const 0)
    (i32.add)
    (i32.load)
    (i32.const 10)
    (i32.const 2)
    (i32.mul)
    (i32.add)
    (i32.store)
    (global.get $sp)
    (i32.const 4)
    (i32.add)
    (i32.load)
    (drop)
    (global.get $sp)
    (i32.const 4)
    (i32.add)
    (i32.load)
    (local.set $ret)
    (global.get $sp)
    (i32.const 8)
    (i32.add)
    (global.set $sp)
    (local.get $ret)
    (return)
    (i32.const 0)
    (local.set $ret)
    (global.get $sp)
    (i32.const 8)
    (i32.add)
    (global.set $sp)
    (local.get $ret)
    (return)
  )
  (func $main (export "main") (result i32)
    (local $t0 i32)
    (local $ret i32)
    (global.get $sp)
    (i32.const 4)
    (i32.sub)
    (global.set $sp)
    (i32.const 5)
    (call $compute)
    (local.set $ret)
    (global.get $sp)
    (i32.const 4)
    (i32.add)
    (global.set $sp)
    (local.get $ret)
    (return)
    (i32.const 0)
    (local.set $ret)
    (global.get $sp)
    (i32.const 4)
    (i32.add)
    (global.set $sp)
    (local.get $ret)
    (return)
  )
)
