#!/usr/bin/env node
/**
 * hincc — Hindawi / PANINI local compiler driver.
 * Copyright (C) 1993-2026 Abhishek Choudhary | GPL-3.0-or-later
 *
 *   .uhin → (language TSV) → flatten/urdu_map → shaili lex → host C/C++ → cc
 *
 * Same kernel as 2004 gurucc. Modern: UTF-8 identifiers, GNU11, configure/make.
 * Keywords come from retrieved shaili filters, not #define.
 */
import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { flatten, applyLang, catalog, BRAHMI, PERSO } from "../runtime/hindawi_port.js";
import { persoToDeva } from "../runtime/perso_arabic.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
let _bundle;
function bundle() {
  if (!_bundle) _bundle = JSON.parse(fs.readFileSync(path.join(root, "docs/engine/bundle.json"), "utf8"));
  return _bundle;
}

function stripShailiPragma(host) {
  return String(host)
    .replace(/<\s*(STYLE|शैली|ਸ਼ੈਲੀ|shailee)[^>]*>/gi, "")
    .replace(/^\s*\n/, "");
}

function indicDigits(s) {
  const d = "०१२३४५६७८९";
  return String(s).replace(/[०-९]/g, (c) => String(d.indexOf(c)));
}

function detectShaili(src) {
  if (/प्राथमिक|praatha/i.test(src)) return "praatha";
  if (/श्रेणी|shraeni/i.test(src)) return "shraeni";
  if (/शब्द|shabda/i.test(src)) return "shabda";
  if (/व्याकरण|व्याक|wyaaka/i.test(src)) return "wyaaka";
  if (/यांत्रिक|yantra/i.test(src)) return "yantra";
  if (/कृत्रिम|kritrima/i.test(src)) return "kritrima";
  if (/सूची|soochee/i.test(src)) return "soochee";
  return "guru";
}

function applyRules(src, rules) {
  const ps = (rules || []).filter((r) => r && r.from && r.to && r.from.length < 48 && !/\s.*,/.test(r.from))
    .slice()
    .sort((a, b) => [...b.from].length - [...a.from].length);
  let i = 0, out = "", s = String(src);
  while (i < s.length) {
    if (s[i] === '"') {
      let j = i + 1;
      while (j < s.length && s[j] !== '"') { if (s[j] === "\\") j += 2; else j++; }
      out += s.slice(i, j + 1); i = j + 1; continue;
    }
    let hit = null;
    for (const r of ps) if (s.startsWith(r.from, i)) { hit = r; break; }
    if (hit) { out += hit.to; i += hit.from.length; }
    else { out += s[i]; i++; }
  }
  return out;
}

function ccOf(shaili) {
  if (shaili === "shraeni") return process.env.CXX || "g++";
  return process.env.CC || "gcc";
}

function extOf(shaili) {
  if (shaili === "shraeni") return ".cpp";
  if (shaili === "kritrima") return ".java";
  if (shaili === "soochee") return ".py";
  if (shaili === "yantra") return ".asm";
  if (shaili === "praatha") return ".bas";
  if (shaili === "shabda") return ".l";
  if (shaili === "wyaaka") return ".y";
  return ".c";
}

export function compileSource(src, opts = {}) {
  const shaili = opts.shaili || detectShaili(src);
  const lang = opts.lang || "hindi";
  const notes = [];
  let stage = String(src);
  if (PERSO.includes(lang)) {
    notes.push("Perso-Arabic: round-trip NOT guaranteed.");
    try { stage = persoToDeva(stage); } catch { /* flatten may still help */ }
  }
  if (lang && lang !== "hindi") {
    try { stage = applyLang(stage, lang); } catch (e) { notes.push("lang TSV: " + e.message); }
  }
  const flattened = flatten(stage);
  const rules = ((bundle().shailis[shaili] || {}).rules) || [];
  let host = applyRules(flattened, rules);
  host = stripShailiPragma(host);
  host = indicDigits(host);
  return {
    invented_maps: false,
    pipeline: "lang-TSV → flatten/urdu_map → shaili lex → host → cc",
    lang, shaili, host: shaili === "shraeni" ? "C++" : "C",
    notes, source: src, flattened, host_text: host, rule_count: rules.length,
  };
}

export function compileFile(file, opts = {}) {
  const src = fs.readFileSync(file, "utf8");
  const r = compileSource(src, opts);
  const base = path.basename(file).replace(/\.(uhin|hin|c|cpp)$/i, "");
  const dir = opts.outdir || path.dirname(path.resolve(file));
  const hostFile = opts.emit || path.join(dir, base + extOf(r.shaili));
  const banner =
    "/* generated by hincc — Hindawi/PANINI\n" +
    " * lang=" + r.lang + " shaili=" + r.shaili + "\n" +
    " * " + r.pipeline + "\n" +
    " * Copyright (C) 1993-2026 Abhishek Choudhary | GPL-3.0-or-later\n" +
    " */\n";
  fs.mkdirSync(path.dirname(hostFile), { recursive: true });
  fs.writeFileSync(hostFile, banner + r.host_text);
  const result = { ...r, hostFile, ok: true };
  const hostOnly = opts.emitOnly || !["guru", "shraeni"].includes(r.shaili);
  if (hostOnly) return result;
  const out = opts.output || path.join(dir, base);
  const cc = opts.cc || ccOf(r.shaili);
  const p = spawnSync(cc, ["-std=gnu11", "-O2", "-o", out, hostFile, "-lm"], { encoding: "utf8" });
  result.cc = cc;
  result.cc_status = p.status;
  result.stderr = p.stderr || "";
  result.bin = out;
  if (p.status !== 0) {
    result.ok = false;
    result.error = (p.stderr || (p.error && p.error.message) || "cc failed").slice(0, 4000);
  }
  return result;
}

function printHelp() {
  const cat = catalog();
  console.log(`hincc — Hindawi local compiler (PANINI)
Usage:
  hincc [--lang hindi] [--shaili guru] [--cc gcc] [--emit-only] [-o bin] file.uhin
  hincc --list
  guru file.uhin          (wrapper: --shaili guru --cc gcc)

2004: guru file   (file.hin, DOS)
2026: hincc file.uhin && ./file

Languages: ${cat.langs.join(", ")}
Shailis:   ${cat.shailis.map((s) => s.id + "=" + s.host).join(", ")}
`);
}

function flag(args, name) {
  const i = args.indexOf("--" + name);
  if (i >= 0) return args[i + 1];
  if (name === "o" || name === "output") {
    const j = args.indexOf("-o");
    if (j >= 0) return args[j + 1];
  }
  const pref = "--" + name + "=";
  const hit = args.find((a) => a.startsWith(pref));
  return hit ? hit.slice(pref.length) : null;
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const args = process.argv.slice(2);
  if (!args.length || args.includes("-h") || args.includes("--help")) { printHelp(); process.exit(0); }
  if (args.includes("--list")) {
    console.log(JSON.stringify({ ...catalog(), brahmi: BRAHMI, perso: PERSO }, null, 2));
    process.exit(0);
  }
  const file = args.filter((a, i) => !a.startsWith("-") && !(args[i - 1] || "").startsWith("--") && args[i - 1] !== "-o").pop();
  if (!file) { printHelp(); process.exit(2); }
  const r = compileFile(file, {
    lang: flag(args, "lang") || "hindi",
    shaili: flag(args, "shaili"),
    cc: flag(args, "cc"),
    output: flag(args, "output") || flag(args, "o"),
    outdir: flag(args, "outdir"),
    emitOnly: args.includes("--emit-only") || args.includes("-E"),
  });
  if (args.includes("--json")) {
    console.log(JSON.stringify({ ok: r.ok, host: r.host, lang: r.lang, shaili: r.shaili, hostFile: r.hostFile, bin: r.bin, error: r.error, preview: (r.host_text || "").slice(0, 400) }, null, 2));
  } else {
    if (r.hostFile) console.error("host " + r.hostFile);
    if (r.bin && r.ok) console.error("bin  " + r.bin);
    if (r.error) { console.error(r.error); process.exit(1); }
  }
  process.exit(r.ok ? 0 : 1);
}
